### ISSUE TITLE
putting a train on itself breaks reality

### ISSUE THREAD

**Issue by JayTheCoderX** [StewStrong/Create-Interactive-Issues#1]
when you move a train using a wrench onto tracks that are on the train it will crash the game and corrupt your world

**Comment by StewStrong** [comment]
I will disable this behavior

**Comment by T0RNATO** [comment]
Do note that this also applies if you try to relocate a train onto tracks that are on a train that is on the original train - nesting also applies.

**Comment by StewStrong** [comment]
I fixed this on the new version (to be released soon)

**Comment by Greenjoe12345** [comment]
It doesn't crash any longer, but now if you place a train onto tracks that are on itself it will instead ascend until a certain point in the sky, then instantly warp back down
