### ISSUE TITLE
Visual bug with train controls placed on already assembled train

### ISSUE THREAD

**Issue by T0RNATO** [StewStrong/Create-Interactive-Issues#4]
The issue in question:
![image](https://github.com/StewStrong/Create-Interactive-Issues/assets/62496453/1f2ef398-5323-45d9-96ab-11acb62684e4)

This is due to the `open` blockstate not being set on the controls - I assume this only happens when the train is initially assembled.

**Comment by StewStrong** [comment]
I fixed this on the new version (to be released soon)

**Comment by Greenjoe12345** [comment]
This still seems to occur.
